# Generated by Django 5.2.3 on 2025-06-20 02:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bicicleta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('MTB', 'Montaña'), ('URB', 'Urbana'), ('EBK', 'Eléctrica')], max_length=3)),
                ('descripcion', models.TextField()),
                ('disponible_para_venta', models.BooleanField(default=True)),
                ('disponible_para_arriendo', models.BooleanField(default=True)),
                ('precio_venta', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('precio_arriendo_hora', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='bicicletas/')),
            ],
        ),
        migrations.CreateModel(
            name='Arriendo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('bicicleta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tienda_masterbikes.bicicleta')),
            ],
        ),
    ]
